// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHy8gAYyYx_0GKEL6I6le9BNLjHJIUNmI',
    appId: '1:624562117894:web:91cc90ca7ba2154169d287',
    messagingSenderId: '624562117894',
    projectId: 'shiftsync-mvp-8593',
    authDomain: 'shiftsync-mvp-8593.firebaseapp.com',
    storageBucket: 'shiftsync-mvp-8593.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbhXXmRanNmLUPotJnQ59kmxnkJnl3DT4',
    appId: '1:624562117894:android:9dac0cbb3ef0729169d287',
    messagingSenderId: '624562117894',
    projectId: 'shiftsync-mvp-8593',
    storageBucket: 'shiftsync-mvp-8593.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGSUOnCz7bebUX1rhOvbiuDdWArzUV6Ns',
    appId: '1:624562117894:ios:c960d40305b873b269d287',
    messagingSenderId: '624562117894',
    projectId: 'shiftsync-mvp-8593',
    storageBucket: 'shiftsync-mvp-8593.firebasestorage.app',
    iosBundleId: 'com.shiftsync.shiftsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGSUOnCz7bebUX1rhOvbiuDdWArzUV6Ns',
    appId: '1:624562117894:ios:c960d40305b873b269d287',
    messagingSenderId: '624562117894',
    projectId: 'shiftsync-mvp-8593',
    storageBucket: 'shiftsync-mvp-8593.firebasestorage.app',
    iosBundleId: 'com.shiftsync.shiftsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHy8gAYyYx_0GKEL6I6le9BNLjHJIUNmI',
    appId: '1:624562117894:web:2554197121162a7a69d287',
    messagingSenderId: '624562117894',
    projectId: 'shiftsync-mvp-8593',
    authDomain: 'shiftsync-mvp-8593.firebaseapp.com',
    storageBucket: 'shiftsync-mvp-8593.firebasestorage.app',
  );
}
